---
- hosts: all
  handlers:
    - name: 'Reinicia apache'
      service:
        name: 'apache2'
        state: 'restarted'
      become: yes

  tasks:

    - name: 'Instala pacotes de dependência do sistema operacional'
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
          - unzip
        state: latest
      become: yes

    - name: 'Cria o banco do MySQL'
      ansible.builtin.mysql_db:
        name: wordpress_db
        login_user: root
        state: present

    - name: 'Cria usuário no banco de dados'
      mysql_user:
        name: reni
        password: 1082
        priv: '*.*:ALL'
        state: present
        login_user: root

    - name: 'Baixa útima versão do wordpress'
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress_latest.zip

    - name: 'Descompactar wordpress.zip'
      unarchive:
        src: /tmp/wordpress_latest.zip
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Realiza cópia do config do Wordpress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Realiza configuração do wp-config com as entradas do banco de dados'
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
          - { regex: 'database_name_here', value: 'wordpress_db' }
          - { regex: 'username_here', value: 'reni' }
          - { regex: 'password_here', value: '1082' }
      become: yes

    - name: 'Configura apache2 para servir o wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - 'Reinicia apache'
