---
- name: 'Instala pacotes de dependência do sistema operacional'
  apt:
    name:
      - php5
      - apache2
      - libapache2-mod-php5
      - php5-gd
      - libssh2-php
      - php5-mcrypt
      - php5-mysql
      - unzip
    state: latest
  become: yes

- name: 'Baixa útima versão do wordpress'
  get_url:
    url: https://wordpress.org/wordpress-5.0.tar.gz
    dest: /tmp/wordpres.tar.gz

- name: 'Descompactar wordpres.tar.gz'
  unarchive:
    src: /tmp/wordpres.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Realiza cópia do config do Wordpress'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Realiza configuração do wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
      - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
      - { regex: 'username_here', value: "{{ wp_db_user }}" }
      - { regex: 'password_here', value: "{{ wp_db_pass }}" }
      - { regex: 'localhost', value: "{{ db_host_ip }}" }
  become: yes

- name: 'Configura o apache2 para servir o wordpress'
  ansible.builtin.template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - 'Reinicia apache'